version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:3306'
