version: '3'

services:
  mysql:
    container_name: backend_mysql
    image: mysql:latest
    restart: always
    # env_file:
    #   - ./.env
    environment:
      MYSQL_USER: custom_user
      MYSQL_PASSWORD: custom_user_pass
      MYSQL_DATABASE: custom_user_db

      # Usando ".env"

      # MYSQL_USER: ${DATABASE_USERNAME}
      # MYSQL_PASSWORD: ${DATABASE_USERNAME}
      # MYSQL_DATABASE: ${DATABASE_USERNAME}

      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
